import { Post } from '../../models/post.model';

export const SOMEPOSTS: Post [] = [
    {
        id: '0',
        title: 'Titulo 1',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '0',
        title: 'Titulo 1',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '0',
        title: 'Titulo 1',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
];

export const POSTS: Post [] = [
    {
        id: '0',
        title: 'Titulo 1',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '1',
        title: 'Titulo 2',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/s.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '2',
        title: 'Titulo 3',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/a.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '3',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/d.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '4',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/f.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '5',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/g.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '6',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/h.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '7',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/j.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '8',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '9',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/l.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '1',
        title: 'Titulo 2',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/s.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '2',
        title: 'Titulo 3',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/a.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '3',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/d.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '4',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/f.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '5',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/g.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '6',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/h.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '7',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/j.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '8',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/k.jpg',
        // likes: 69,
        // comments: ,
    },
    {
        id: '9',
        title: 'Titulo 4',
        date: new Date(),
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
        image: 'assets/images/l.jpg',
        // likes: 69,
        // comments: ,
    },

];
